'use client'
import { useRouter } from 'next/navigation'

export default function Home() {
  const Router = useRouter()
  return (
    // <div className="min-h-screen flex flex-col">
    //   <main className="flex-grow container mx-auto p-6 text-gray-800">
    //     <section className="my-10 text-center">
    //       <h2 className="text-4xl font-semibold">
    //         Welcome to MockMaster ProPrep
    //       </h2>
    //       <p className="mt-4 text-lg">
    //         MockMaster ProPrep is a groundbreaking web application that conducts
    //         mock interviews using AI. Our platform generates interview questions
    //         tailored to your job role, and you can answer them through your
    //         voice. AI provides feedback on your responses with ratings to help
    //         you improve.
    //       </p>
    //     </section>

    //     <section className="my-10">
    //       <h2 className="text-3xl font-semibold text-center">Features</h2>
    //       <div className="flex flex-wrap justify-center mt-6">
    //         <div className="max-w-sm w-full lg:max-w-full lg:flex">
    //           <div className="border border-gray-400 bg-white p-6 rounded-lg shadow-lg m-4 flex-1">
    //             <h3 className="text-2xl font-bold">AI-Generated Questions</h3>
    //             <p className="mt-2 text-lg">
    //               Get questions tailored to your specific job role, generated by
    //               our advanced AI.
    //             </p>
    //           </div>
    //         </div>
    //         <div className="max-w-sm w-full lg:max-w-full lg:flex">
    //           <div className="border border-gray-400 bg-white p-6 rounded-lg shadow-lg m-4 flex-1">
    //             <h3 className="text-2xl font-bold">Voice Responses</h3>
    //             <p className="mt-2 text-lg">
    //               Answer the questions using your voice for a more realistic
    //               interview experience.
    //             </p>
    //           </div>
    //         </div>
    //         <div className="max-w-sm w-full lg:max-w-full lg:flex">
    //           <div className="border border-gray-400 bg-white p-6 rounded-lg shadow-lg m-4 flex-1">
    //             <h3 className="text-2xl font-bold">AI Feedback</h3>
    //             <p className="mt-2 text-lg">
    //               Receive detailed feedback and ratings on your responses to
    //               help you improve.
    //             </p>
    //           </div>
    //         </div>
    //       </div>
    //     </section>

    //     <section className="my-10 text-center">
    //       <h2 className="text-3xl font-semibold">Get Started</h2>
    //       <p className="mt-4 text-lg">
    //         Join MockMaster ProPrep today and take your interview skills to the
    //         next level!
    //       </p>
    //       <button
    //         onClick={() => Router.push('/DashBoard')}
    //         className="mt-6 px-6 py-3 bg-blue-500 text-white font-bold rounded-full hover:bg-blue-700"
    //       >
    //         Sign Up Now
    //       </button>
    //     </section>
    //   </main>

    //   <footer className="bg-gray-800 p-6 text-white text-center">
    //     <p>&copy; 2024 MockMaster ProPrep. All rights reserved.</p>
    //   </footer>
    // </div>
    <main className=" p-3">
      <AddInterview />
    </main>
  )
}
